version: 2

jobs:
  build:
    macos:
      xcode: "9.0"

    environment:
      TRAVIS_BRANCH: $CIRCLE_BRANCH
      TRAVIS_OS_NAME: osx
      TRAVIS_PULL_REQUEST: $CI_PULL_REQUEST || "false"

    steps:
      - run:
          name: Switch timezone to America/New_York
          command: sudo systemsetup -settimezone 'America/New_York'

      - checkout

      - run: bin/ci prepare_system
      - run: bin/ci prepare_build
      - run: bin/ci build
